#!/usr/bin/env bash
# snatched from
#   http://tools.suckless.org/dmenu/scripts/

shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | rofi -dmenu -p "" "$@")

[[ -n $password ]] || exit

xdotool - <<<"type --clearmodifiers -- $(pass show "$password" | head -n 1)"
